FROM node:16-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --location=global
COPY . .
RUN yarn build && ls -la ./dist


FROM node:16-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./
COPY ormconfig.js .
ENV JWT_SECRET="4125442A472D4B6150645367556B58703273357638792F423F4528482B4D6251"
ENV JWT_REFRESH_SECRET="576E5A7134743777217A25432A462D4A614E645267556B58703273357538782F"
EXPOSE 5000
CMD ["yarn", "start:prod"]